# .sass-lint.yml
options:
  formatter: stylish
files:
  include: '_sass/**/*.scss'
rules:
  indentation:
    - 2
    - size: 4
  property-sort-order:
    - 1
    - order: alphabetical
  no-color-literals: 0
  no-ids: 0
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
  nesting-depth:
    - 1
    - max-depth: 4
  no-important: 1
  no-duplicate-properties: 2