name: Deploy Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer

      - name: Generate PDF
        run: |
          cat << 'EOF' > generate-pdf.js
          const puppeteer = require('puppeteer');
          const fs = require('fs');
          
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            
            // Load the HTML file
            await page.goto(`file:${process.cwd()}/index.html`, {
              waitUntil: 'networkidle0'
            });
            
            // Create PDF
            await page.pdf({
              path: 'resume.pdf',
              format: 'A4',
              margin: {
                top: '20px',
                right: '20px',
                bottom: '20px',
                left: '20px'
              }
            });
            
            await browser.close();
          })();
          EOF
          node generate-pdf.js

      - name: Validate HTML
        run: |
          npx html-validate index.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          # Optional: Add custom domain if you have one
          # cname: your-domain.com

      # Upload PDF as artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
          if-no-files-found: error

      # Create release with PDF if this is a tag
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}