name: Deploy Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug step to understand the environment
      - name: Debug Environment
        run: |
          echo "Current working directory: $PWD"
          echo "Directory contents:"
          ls -la
          echo "Repository root contents:"
          ls -la $GITHUB_WORKSPACE
          echo "Git status:"
          git status

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer

      # Prepare site directory with explicit paths
      - name: Prepare deployment
        run: |
          echo "Creating _site directory..."
          mkdir -p _site
          
          echo "Copying files with full paths..."
          echo "Current directory: $(pwd)"
          echo "Files available:"
          ls -la
          
          # Copy files with error checking
          for file in index.html styles.css; do
            if [ -f "$file" ]; then
              echo "Copying $file..."
              cp "$file" _site/
            else
              echo "Warning: $file not found in $(pwd)"
              exit 1
            fi
          done
          
          # Generate PDF before copying
          echo "Generating PDF..."
          node generate-pdf.js
          
          if [ -f "resume.pdf" ]; then
            echo "Copying resume.pdf..."
            cp resume.pdf _site/
          else
            echo "Warning: resume.pdf not found"
            exit 1
          fi
          
          echo "Final _site contents:"
          ls -la _site/

      - name: Validate HTML
        run: |
          npx html-validate index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
          if-no-files-found: error

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}