name: 'Security Analysis'

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 on the first of every month
  workflow_dispatch:      # Manual trigger option

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./