name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Jekyll
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          npm install jest @testing-library/jest-dom @testing-library/dom puppeteer axe-core lighthouse
          npm install --save-dev jest-environment-jsdom

      - name: Run Tests
        run: npm test

      # Performance testing with Lighthouse
      - name: Lighthouse Check
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun || echo "Lighthouse failed"

      # Accessibility testing
      - name: Run accessibility tests
        run: node tests/accessibility.js

      # Visual regression testing
      - name: Run visual regression tests
        run: node tests/visual-regression.js

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            tests/results
            .lighthouseci