name: Test

on:
  push:
  workflow_dispatch:
    inputs:
      update_baseline:
        description: 'Update visual regression baseline'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Jekyll
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm ci
          npm install jest @testing-library/jest-dom @testing-library/dom puppeteer axe-core lighthouse
          npm install --save-dev jest-environment-jsdom
          npm install -D @playwright/test pngjs pixelmatch

      - name: Install Playwright and browsers
        run: |
          npx playwright install chromium
          npx playwright install-deps chromium

      # Download baseline if it exists
      - name: Download baseline image
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: visual-regression-baseline
          path: tests/

      - name: Run Tests
        run: npm test

      - name: Custom Performance Tests
        run: node tests/performance.js

      - name: Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Lighthouse Status Check
        if: github.event_name == 'pull_request'
        run: |
          score=$(cat .lighthouseci/manifest.json | jq -r '.[] | .summary.performance')
          if (( $(echo "$score < 0.9" | bc -l) )); then
            echo "Performance score below threshold: $score"
            exit 1
          fi

      - name: Run accessibility tests
        run: node tests/accessibility.js

      - name: Run visual regression tests
        run: node tests/visual-regression.js
        env:
          UPDATE_VISUAL_BASELINE: ${{ github.event_name == 'workflow_dispatch' && inputs.update_baseline == 'true' || github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Upload baseline image
        if: success() || env.UPDATE_VISUAL_BASELINE == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: visual-regression-baseline
          path: tests/baseline.png
          retention-days: 1

      - name: Upload baseline image
        if: success() || github.event_name == 'workflow_dispatch' && inputs.update_baseline == 'true' || github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: visual-regression-baseline
          path: tests/baseline.png
          retention-days: 1
