name: Update Visual Regression Baseline

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure you want to update the baseline? This will accept current visual changes as the new standard.'
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  update-baseline:
    if: inputs.confirm == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Build Jekyll
        run: npm run build
      - run: npm run test:visual
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Commit new baseline
        run: |
          cp tests/results/current.png tests/baseline.png
          git add tests/baseline.png
          git commit -m "chore: update visual regression baseline"
          git push
